version: '3'

services:
  # Database
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ehsan
      MYSQL_DATABASE: ehsan
      MYSQL_USER: ehsan
      MYSQL_PASSWORD: ehsan
    networks:
      - ehapi
  ehsan-core-api-containerv1:
    build: .
    container_name: "ehsan-core-api-containerv1"
    ports:
      - "8000:8000"
    volumes:
      - api_data:/app
    depends_on:
      - db
networks:
  ehapi:
volumes:
  db_data:
  api_data:
