version: "3"

services:
  mysql:
    container_name: mysql_db
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
    ports:
      - "3308:3306"
    restart: always

  core-api:
    build: .
    container_name: "core-api-container"
    ports:
      - "8000:8000"
    volumes:
      - ./fast-api:/app
    depends_on:
      - mysql
