version: "3"

services:
  core-api:
    build: .
    container_name: "core-api-container"
    ports:
    - "8000:15400"
    volumes:
    - ./fast-api:/app
#
#  db:
#    image: mysql:11
#    ports:
#      - "5432:5432"
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_DB=test_db
#  web:
#    build: .
#    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
#    volumes:
#      - .:/code
#    ports:
#      - "8000:8000"
#    depends_on:
#      - db
#
#  mysql:
#    container_name: mysql
#    image: dpage/mysql
#    environment:
#      - MYSQL_DEFAULT_EMAIL=root
#      - MYSQL_DEFAULT_PASSWORD=mysql
#    ports:
#      - "5050:80"
#    depends_on:
#      - db