"""create table

Revision ID: 7fa3257a4281
Revises: 84e7580ec14b
Create Date: 2021-03-21 16:39:54.331799

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7fa3257a4281'
down_revision = '84e7580ec14b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('found_items', sa.Column('found_longitude', sa.Float(), nullable=True))
    op.drop_column('found_items', 'found_longitude')
    op.add_column('lost_items', sa.Column('lost_longitude', sa.Float(), nullable=True))
    op.drop_column('lost_items', 'lost_longitude')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lost_items', sa.Column('lost_longitude', mysql.FLOAT(), nullable=True))
    op.drop_column('lost_items', 'lost_longitude')
    op.add_column('found_items', sa.Column('found_longitude', mysql.FLOAT(), nullable=True))
    op.drop_column('found_items', 'found_longitude')
    # ### end Alembic commands ###
