"""create table

Revision ID: 84e7580ec14b
Revises: 0b35dbe13d1a
Create Date: 2021-03-21 16:35:26.957040

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '84e7580ec14b'
down_revision = '0b35dbe13d1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('found_items', sa.Column('found_item_id', sa.Integer(), nullable=False))
    op.add_column('found_items', sa.Column('lost_item_id', sa.Integer(), nullable=True))
    op.drop_index('ix_found_items_found_items_id', table_name='found_items')
    op.create_index(op.f('ix_found_items_found_item_id'), 'found_items', ['found_item_id'], unique=False)
    op.create_foreign_key(None, 'found_items', 'lost_items', ['lost_item_id'], ['lost_item_id'])
    op.drop_column('found_items', 'found_items_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('found_items', sa.Column('found_items_id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'found_items', type_='foreignkey')
    op.drop_index(op.f('ix_found_items_found_item_id'), table_name='found_items')
    op.create_index('ix_found_items_found_items_id', 'found_items', ['found_items_id'], unique=False)
    op.drop_column('found_items', 'lost_item_id')
    op.drop_column('found_items', 'found_item_id')
    # ### end Alembic commands ###
