"""create users table

Revision ID: 96b5db7d5fb3
Revises: 7fa3257a4281
Create Date: 2021-03-21 16:46:10.257723

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '96b5db7d5fb3'
down_revision = '7fa3257a4281'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('found_items', sa.Column('found_longitude', sa.Float(), nullable=True))
    op.drop_column('found_items', 'found_longitudee')
    op.add_column('lost_items', sa.Column('lost_longitude', sa.Float(), nullable=True))
    op.drop_column('lost_items', 'lost_longitudee')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lost_items', sa.Column('lost_longitudee', mysql.FLOAT(), nullable=True))
    op.drop_column('lost_items', 'lost_longitude')
    op.add_column('found_items', sa.Column('found_longitudee', mysql.FLOAT(), nullable=True))
    op.drop_column('found_items', 'found_longitude')
    # ### end Alembic commands ###
